name: teddy_sign_in
description: A Flutter Project For Real Sign In Page Based on Flare Teddy animation

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flare_flutter:
    git: https://github.com/GJJ2019AppSynergies/Flare-Flutter.git
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf


